version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: nextjs
      POSTGRES_PASSWORD: nextjs
      POSTGRES_DB: nextjs
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextjs -d nextjs"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
